version: '3.7'
services:
  pgdatabase:
    container_name: pgdatabase
    image: postgres:13
    environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=ny_taxi
    volumes:
        - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
        - "5431:5431"
    networks:
        - pg-network
    

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
        - PGADMIN_DEFAULT_EMAIL=admin@admin.com
        - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - "pg-admin:/var/lib/pgadmin"      
    ports:
        - "8079:80"
    networks:
        - pg-network
    depends_on:
        - pgdatabase

volumes:
  pg-admin:   

networks:
  pg-network:     
